danger_zone1:
  - {x: 0.0, y: 0.0}
  - {x: -0.60, y: 0.48}  # Up
  - {x: -0.60, y: 1.8}   # Left
  - {x: 0.60, y: 1.8}    # Down
  - {x: 0.60, y: 0.48}   # Right

danger_zone2:
  - {x: 0.0, y: 0.0}
  - {x: -0.50, y: 0.48}  # Up
  - {x: -0.50, y: 1.6}   # Left
  - {x: 0.50, y: 1.6}    # Down
  - {x: 0.50, y: 0.48}   # Right

danger_zone3:
  - {x: 0.0, y: 0.0}
  - {x: -0.50, y: 0.48}  # Up
  - {x: -0.50, y: 1.0}   # Left
  - {x: 0.50, y: 1.0}    # Down
  - {x: 0.50, y: 0.48}   # Right

warning_zone:
  - {x: 0.0, y: 0.0}
  - {x: 0.94, y: 0.28}   # Up
  - {x: 0.84, y: 2.1}    # Left
  - {x: -0.84, y: 2.1}   # Down
  - {x: -0.94, y: 0.28}  # Right
