controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    drive_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    steering_position_controller:
      type: position_controllers/JointGroupPositionController

    lift_controller:
      type: position_controllers/JointGroupPositionController

drive_velocity_controller:
  ros__parameters:
    joints:
      - drive_wheel_joint

steering_position_controller:
  ros__parameters:
    joints:
      - drive_wheel_Ass_joint

lift_controller:
  ros__parameters:
    joints:
      - front_lift_joint
