controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tricycle_controller:
      type: tricycle_controller/TricycleController

    lift_controller:
      type: position_controllers/JointGroupPositionController

tricycle_controller:
  ros__parameters:
    traction_joint_name: drive_wheel_joint
    steering_joint_name: drive_wheel_Ass_joint
    wheel_radius: 0.05215
    wheelbase: 1.2981

lift_controller:
  ros__parameters:
    joints:
      - front_lift_joint
