#!/usr/bin/env python3

from typing import List

import numpy as np

from builtin_interfaces.msg import Duration
from geometry_msgs.msg import Point
from std_msgs.msg import ColorRGBA
from visualization_msgs.msg import Marker, MarkerArray

from models.cluster import Cluster, ROICluster, ClusterQuality


class ClusterVisualizer:
    """
    Visualizes clusters in RViz.

    Expected structure:

        ROICluster
            ├── roi
            └── clusters
                  ├── Cluster
                  ├── Cluster
                  └── ...

    Each Cluster is visualized using:

        1. Bounding box
        2. Compact quality label

    Marker IDs are generated by this visualizer and are always
    valid integers.
    """

    def __init__(
        self,
        frame_id: str = "load_wheel_base_link",
        namespace: str = "clusters",
    ):

        self.frame_id = frame_id
        self.namespace = namespace

        # ======================================================
        # Fallback cluster colors
        # ======================================================

        self.colors = [
            ColorRGBA(r=1.0, g=0.0, b=0.0, a=1.0),  # Red
            ColorRGBA(r=0.0, g=1.0, b=0.0, a=1.0),  # Green
            ColorRGBA(r=0.0, g=0.0, b=1.0, a=1.0),  # Blue
            ColorRGBA(r=1.0, g=1.0, b=0.0, a=1.0),  # Yellow
            ColorRGBA(r=1.0, g=0.0, b=1.0, a=1.0),  # Magenta
            ColorRGBA(r=0.0, g=1.0, b=1.0, a=1.0),  # Cyan
        ]

        # ======================================================
        # Quality colors
        # ======================================================

        self.quality_colors = {
            ClusterQuality.VALID:
                ColorRGBA(
                    r=0.0,
                    g=1.0,
                    b=0.0,
                    a=1.0,
                ),

            ClusterQuality.WEAK:
                ColorRGBA(
                    r=1.0,
                    g=1.0,
                    b=0.0,
                    a=1.0,
                ),

            ClusterQuality.SUSPICIOUS:
                ColorRGBA(
                    r=1.0,
                    g=0.0,
                    b=0.0,
                    a=1.0,
                ),
        }

    # ==========================================================
    # Public API
    # ==========================================================

    def create_markers(
        self,
        roi_clusters: List[ROICluster],
    ) -> MarkerArray:
        """
        Create RViz markers for all current clusters.

        Every call starts with DELETEALL so that markers from a
        previous frame cannot remain in RViz after the number of
        clusters changes.
        """

        marker_array = MarkerArray()

        # ------------------------------------------------------
        # Remove markers from previous frame
        # ------------------------------------------------------

        delete_marker = Marker()

        delete_marker.action = Marker.DELETEALL

        marker_array.markers.append(
            delete_marker
        )

        if not roi_clusters:
            return marker_array

        # ------------------------------------------------------
        # Generate current markers
        # ------------------------------------------------------

        for roi_index, roi_cluster in enumerate(
            roi_clusters
        ):

            if roi_cluster is None:
                continue

            clusters = getattr(
                roi_cluster,
                "clusters",
                None,
            )

            if not clusters:
                continue

            for cluster_index, cluster in enumerate(
                clusters
            ):

                if cluster is None:
                    continue

                if cluster.cloud is None:
                    continue

                if cluster.cloud.is_empty:
                    continue

                points = cluster.cloud.points

                if points is None:
                    continue

                if len(points) == 0:
                    continue

                # --------------------------------------------------
                # Marker ID
                # --------------------------------------------------

                marker_id = self._marker_id(
                    roi_index=roi_index,
                    cluster_index=cluster_index,
                )

                # --------------------------------------------------
                # Bounding box
                # --------------------------------------------------

                bbox_marker = (
                    self._create_bbox_marker(
                        cluster=cluster,
                        marker_id=marker_id,
                        cluster_index=cluster_index,
                    )
                )

                marker_array.markers.append(
                    bbox_marker
                )

                # --------------------------------------------------
                # Text
                # --------------------------------------------------

                text_marker = (
                    self._create_text_marker(
                        cluster=cluster,
                        roi_cluster=roi_cluster,
                        marker_id=marker_id,
                        cluster_index=cluster_index,
                    )
                )

                marker_array.markers.append(
                    text_marker
                )

        return marker_array

    # ==========================================================
    # Marker IDs
    # ==========================================================

    def _marker_id(
        self,
        roi_index: int,
        cluster_index: int,
    ) -> int:
        """
        Generate a deterministic integer marker ID.

        Range:

            ROI 0, cluster 0 -> 1000
            ROI 0, cluster 1 -> 1001
            ROI 1, cluster 0 -> 2000

        IDs remain valid ROS integer IDs and bbox/text markers
        use separate namespaces.
        """

        return int(
            (roi_index + 1) * 1000
            + cluster_index
        )

    # ==========================================================
    # Color
    # ==========================================================

    def _color(
        self,
        cluster_index: int,
    ) -> ColorRGBA:
        """
        Return a fallback color based on cluster index.
        """

        return self.colors[
            cluster_index % len(self.colors)
        ]

    # ----------------------------------------------------------

    def _quality_color(
        self,
        cluster: Cluster,
        cluster_index: int,
    ) -> ColorRGBA:
        """
        Select the bounding-box color based on cluster quality.

        VALID       -> Green
        WEAK        -> Yellow
        SUSPICIOUS  -> Red

        Unknown quality falls back to the cluster index color.
        """

        quality = getattr(
            cluster,
            "quality",
            None,
        )

        if quality in self.quality_colors:

            return self.quality_colors[
                quality
            ]

        return self._color(
            cluster_index
        )

    # ==========================================================
    # Bounding Box
    # ==========================================================

    def _create_bbox_marker(
        self,
        cluster: Cluster,
        marker_id: int,
        cluster_index: int,
    ) -> Marker:
        """
        Create a 2D bounding box around a cluster.
        """

        points = cluster.cloud.points

        # ------------------------------------------------------
        # Calculate bounds
        # ------------------------------------------------------

        min_x = float(
            np.min(points[:, 0])
        )

        max_x = float(
            np.max(points[:, 0])
        )

        min_y = float(
            np.min(points[:, 1])
        )

        max_y = float(
            np.max(points[:, 1])
        )

        marker = Marker()

        # ------------------------------------------------------
        # Header
        # ------------------------------------------------------

        marker.header.frame_id = (
            self.frame_id
        )

        # ------------------------------------------------------
        # Namespace / ID
        # ------------------------------------------------------

        marker.ns = self.namespace

        marker.id = int(
            marker_id
        )

        # ------------------------------------------------------
        # Type
        # ------------------------------------------------------

        marker.type = Marker.LINE_STRIP

        marker.action = Marker.ADD

        # ------------------------------------------------------
        # Line width
        # ------------------------------------------------------

        marker.scale.x = 0.02

        # ------------------------------------------------------
        # Quality color
        # ------------------------------------------------------

        marker.color = (
            self._quality_color(
                cluster,
                cluster_index,
            )
        )

        # ------------------------------------------------------
        # Lifetime
        # ------------------------------------------------------

        marker.lifetime = Duration(
            sec=0
        )

        # ------------------------------------------------------
        # Bounding box corners
        # ------------------------------------------------------

        corners = [
            (min_x, min_y),
            (max_x, min_y),
            (max_x, max_y),
            (min_x, max_y),
            (min_x, min_y),
        ]

        for x, y in corners:

            point = Point()

            point.x = float(x)
            point.y = float(y)
            point.z = 0.0

            marker.points.append(
                point
            )

        return marker

    # ==========================================================
    # Text Marker
    # ==========================================================

    def _create_text_marker(
        self,
        cluster: Cluster,
        roi_cluster: ROICluster,
        marker_id: int,
        cluster_index: int,
    ) -> Marker:
        """
        Create a compact label above the cluster bounding box.

        Example:

            C0 VALID
            C1 WEAK
            C2 SUSPICIOUS
        """

        points = cluster.cloud.points

        # ------------------------------------------------------
        # Bounding box
        # ------------------------------------------------------

        min_x = float(
            np.min(points[:, 0])
        )

        max_x = float(
            np.max(points[:, 0])
        )

        min_y = float(
            np.min(points[:, 1])
        )

        max_y = float(
            np.max(points[:, 1])
        )

        # ------------------------------------------------------
        # Put text at top-center of bounding box
        # ------------------------------------------------------

        center_x = (
            min_x + max_x
        ) / 2.0

        label_y = max_y

        # ------------------------------------------------------
        # Slight vertical offset
        # ------------------------------------------------------

        label_z = 0.20

        marker = Marker()

        # ------------------------------------------------------
        # Header
        # ------------------------------------------------------

        marker.header.frame_id = (
            self.frame_id
        )

        # ------------------------------------------------------
        # Namespace / ID
        # ------------------------------------------------------

        marker.ns = (
            self.namespace
            + "_text"
        )

        marker.id = int(
            marker_id + 100000
        )

        # ------------------------------------------------------
        # Type
        # ------------------------------------------------------

        marker.type = (
            Marker.TEXT_VIEW_FACING
        )

        marker.action = Marker.ADD

        # ------------------------------------------------------
        # Position
        # ------------------------------------------------------

        marker.pose.position.x = (
            float(center_x)
        )

        marker.pose.position.y = (
            float(label_y)
        )

        marker.pose.position.z = (
            float(label_z)
        )

        # ------------------------------------------------------
        # Text size
        # ------------------------------------------------------

        marker.scale.z = 0.15

        # ------------------------------------------------------
        # Text color
        # ------------------------------------------------------

        marker.color.r = 1.0
        marker.color.g = 1.0
        marker.color.b = 1.0
        marker.color.a = 1.0

        # ------------------------------------------------------
        # Quality
        # ------------------------------------------------------

        quality = getattr(
            cluster,
            "quality",
            None,
        )

        if quality is not None:

            quality_name = getattr(
                quality,
                "name",
                str(quality),
            )

        else:

            quality_name = "UNKNOWN"

        # ------------------------------------------------------
        # Compact label
        # ------------------------------------------------------

        # marker.text = (
        #     f"C{cluster_index} "
        #     f"{quality_name}"
        # )

        # ------------------------------------------------------
        # Lifetime
        # ------------------------------------------------------

        marker.lifetime = Duration(
            sec=0
        )

        return marker